name: Build and Deploy to AKS

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: myapp

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Set ACR Login Server
      id: acr
      run: |
        echo "##[set-output name=loginServer;]${{ secrets.ACR_NAME }}.azurecr.io"
    - name: Build and Push Docker image to ACR
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}
        docker build -t ${{ steps.acr.outputs.loginServer }}/${{ env.IMAGE_NAME }}:latest -f DockerFile .
        docker push ${{ steps.acr.outputs.loginServer }}/${{ env.IMAGE_NAME }}:latest
    - name: Get AKS Credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }} --overwrite-existing
    - name: Deploy to AKS
      run: |
        kubectl set image deployment/${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }}=${{ steps.acr.outputs.loginServer }}/${{ env.IMAGE_NAME }}:latest --record || \
        kubectl create deployment ${{ env.IMAGE_NAME }} --image=${{ steps.acr.outputs.loginServer }}/${{ env.IMAGE_NAME }}:latest
